### ISSUE TITLE
Command 'ps' required by nextflow to collect task metrics cannot be found

### ISSUE THREAD

**Issue by sarah-chapin** [salzmanlab/ReadZS#8]
Hello, 

I am using the singularity profile to run the pipeline with the following command:

`nextflow run salzmanlab/readzs \
    -r master \
    -latest \
    -profile singularity \
    --runName "small_test_data" \
    --input "https://raw.githubusercontent.com/salzmanlab/ReadZS/master/small_test_data/samplesheet.csv" \
    --chr_lengths "https://raw.githubusercontent.com/salzmanlab/ReadZS/master/small_test_data/refs/chrLength.txt" \
    --useChannels true \
    --libType "10X" \
    --isSICILIAN true \
    --isCellranger false \
    --metadata "https://raw.githubusercontent.com/salzmanlab/ReadZS/master/small_test_data/refs/meta.tsv" \
    --minCellsPerWindowOnt 10 \
    --minCtsPerCell 5 \
    --ontologyCols "'compartment, tissue'" \
    --annotation_bed "https://raw.githubusercontent.com/salzmanlab/ReadZS/master/small_test_data/refs/hg38.genes.bed" \
    --gff small_test_data/refs/small.gff `

During the CALL_PEAKS process I receive the following error: 
Command 'ps' required by nextflow to collect task metrics cannot be found

From the Nextflow documentation [here](https://www.nextflow.io/docs/latest/tracing.html#tasks), the ps tool is required by Nextflow for certain tasks. Is it possible to add ps to the singularity profile?

**Comment by kaitlinchaung** [comment]
Thanks Sarah! I'll add that to the container today.

**Comment by sarah-chapin** [comment]
Great, thank you. Please let me know when it's updated and I'll test it again.

**Comment by kaitlinchaung** [comment]
Hi Sarah, apologies for the delays. The container _should_ be up to date now, please let me know if there are any further issues

**Comment by kaitlinchaung** [comment]
Hi Sarah, my apologies for the delay! I have updated the container to address the issue, please let me know if there are still container issues. Thanks!

**Comment by sarah-chapin** [comment]
Looks like the container issue resolved. Thanks!
